### ISSUE TITLE
prov/lnx: error when sending to self with xpmem

### ISSUE THREAD

**Issue by angainor** [ofiwg/libfabric#11285]
In OpenMPI, when using `lnx` with `shm` and `FI_SHM_USE_XPMEM=1` a rank fails to send messages above certain size to itself.

**To Reproduce**
Compile the attached program. For messages of 512 and fewer `double` values the program runs fine:
```
mpirun -np 2 -x FI_SHM_USE_XPMEM=1 -x FI_LNX_PROV_LINKS="shm" -mca pml cm -mca mtl ofi --mca opal_common_ofi_provider_include "lnx" -mca mtl_ofi_av table -prtemca ras_base_launch_orted_on_hn 1  ./mpi-test 512
OK
OK
```

But for larger buffers the communication fails:
```
mpirun -np 2 -x FI_SHM_USE_XPMEM=1 -x FI_LNX_PROV_LINKS="shm" -mca pml cm -mca mtl ofi --mca opal_common_ofi_provider_include "lnx" -mca mtl_ofi_av table -prtemca ras_base_launch_orted_on_hn 1  ./mpi-test 513
[x1001c1s1b0n3:00000] *** An error occurred in MPI_Waitall
[x1001c1s1b0n3:00000] *** reported by process [3355574273,1]
[x1001c1s1b0n3:00000] *** on communicator MPI_COMM_WORLD
[x1001c1s1b0n3:00000] *** MPI_ERR_INTERN: internal error
[x1001c1s1b0n3:00000] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[x1001c1s1b0n3:00000] ***    and MPI will try to terminate your MPI job as well)
```
The program runs when I turn off xpemem:
```
mpirun -np 2 -x FI_SHM_USE_XPMEM=0 -x FI_LNX_PROV_LINKS="shm" -mca pml cm -mca mtl ofi --mca opal_common_ofi_provider_include "lnx" -mca mtl_ofi_av table -prtemca ras_base_launch_orted_on_hn 1  ./mpi-test 513
OK
OK
```

**Environment:**
Running on Cray/HPE SLES, libfabric from `main:b4d66113d3b49b927c529067beb7ab7cf6465564`, OpenMPI 5.0.7

**Additional context**
This is the simple reproducer:
```
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{
  MPI_Request *req_buffer;
  int rank, size, buff_size = atoi(argv[1]);

  MPI_Init (&argc, &argv);
  MPI_Comm_rank (MPI_COMM_WORLD, &rank);
  MPI_Comm_size (MPI_COMM_WORLD, &size);
  req_buffer = malloc(sizeof(MPI_Request)*size);
  
  double *send_buffer = (double*)calloc(sizeof(double),buff_size);
  double *recv_buffer = (double*)calloc(sizeof(double),buff_size);
  
  MPI_Isend (send_buffer, buff_size, MPI_DOUBLE,
	     rank, 10, MPI_COMM_WORLD,
	     req_buffer+1);
  MPI_Irecv (recv_buffer, buff_size, MPI_DOUBLE,
	     rank, 10, MPI_COMM_WORLD,
	     req_buffer+0);   
  MPI_Waitall (2, req_buffer+0, MPI_STATUSES_IGNORE);
  printf("OK\n");
  MPI_Finalize();
}
```
Compile with `mpicc mpi-test.c -o mpi-test`

**Comment by jfillers** [comment]
I am able to verify this is now working with the latest libfabric `main:183bb2c06d57e41f6a919e41ebc2e34c08196aad` and OpenMPI `main:3a2e90895e15822912002be1e9aea8032c4c0bae`.

I am currently testing on a system with the same architecture as Frontier with the following modules loaded:
```
Currently Loaded Modules:
  1) craype-x86-trento        3) Core/25.03   5) DefApps         7) cray-dsmml/0.3.0      9) PrgEnv-gnu/8.6.0  11) json-c/0.17              13) openmpi/main-tfillers    15) rocm/6.2.4
  2) perftools-base/24.11.0   4) tmux/3.4     6) craype/2.7.33   8) cray-libsci/24.11.0  10) gcc-native/14.2   12) libfabric/main-tfillers  14) craype-accel-amd-gfx90a  16) xpmem/2.11.3-1.3_gdbda01a1eb3d
```
Note: The OpenMPI and libfabric modules are the versions previously mentioned. 

I can successfully execute the reproducer with the following command:
```
mpirun -np 2 -x FI_SHM_USE_XPMEM=1 -x FI_LNX_PROV_LINKS="shm" -mca pml cm -mca mtl ofi --mca opal_common_ofi_provider_include "lnx" -mca mtl_ofi_av table -prtemca ras_base_launch_orted_on_hn 1 ./reproducer 4096
OK
OK
```

**Comment by aingerson** [comment]
@jfillers Sorry we didn't take a look earlier but I'm glad your problem has been resolved! I don't see anything in the recent changes that would explain any difference in behavior for you but perhaps it was some weird side effect. Please close if you feel like your issue isn't an issue anymore. Thank you!

**Comment by angainor** [comment]
@aingerson @jfillers I just checked with OpenMPI `main:4b2fc510b1b4511b0a75a82a3ada671d3cf9e690` and libfabric `main:f08ec6a6c549c83de576bfcf85b92189364d38d7`, and I still reproduce the problem.

**Comment by aingerson** [comment]
@amirshehataornl Any thoughts on this?

**Comment by JenningsI** [comment]
I like this test for showing this prov/lnx issue but it needs an extra step to complete it.
On some machines I see MPI_ERR_INTERN and on others I see OK OK even though the test has really failed.

If I run the test with FI_LOG_LEVEL=info and grep the output for Using, on the tests that show MPI_ERR_INTERN I see:
libfabric:  ... Using cxi provider ...
libfabric:  ... Using lnx provider ...
libfabric:  ... Using shm provider ...

and on the tests that show OK OK I only see:
libfabric:  ... Using cxi provider ...
