### ISSUE TITLE
prov/rxm: server_sock_accept() error

### ISSUE THREAD

**Issue by yulujia** [ofiwg/libfabric#5296]
using commit: 3712eb04919fb9542659da326d295734d974013d

I ran a test we have using the tcp provider, after the clients connect/disconnect for a few cycles, the server side starts to print out a lot of messages like the following, and test gets stuck:

= = = = = = = = = = = = = = = = = = = = = = 
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:ofi_rxm:ep_ctrl:rxm_msg_ep_open():825<warn> unable to create msg_ep: -24
libfabric:128018:ofi_rxm:ep_ctrl:rxm_msg_ep_open():825<warn> unable to create msg_ep: -24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:ofi_rxm:ep_ctrl:rxm_msg_ep_open():825<warn> unable to create msg_ep: -24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:ofi_rxm:ep_ctrl:rxm_msg_ep_open():825<warn> unable to create msg_ep: -24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:ofi_rxm:ep_ctrl:rxm_msg_ep_open():825<warn> unable to create msg_ep: -24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
libfabric:128018:tcp:ep_ctrl:server_sock_accept():395<warn> accept error: 24
= = = = = = = = = = = = = = = = = = = = = =

**Comment by shefty** [comment]
Updated issue title to refer to rxm provider, since that's the top level provider in use based on the log.

**Comment by shefty** [comment]
Can you describe the test in more detail, specifically the part about disconnecting?  RxM is referenced in the logs, which uses RDM endpoints.

**Comment by yulujia** [comment]
the test starts 4 server processes on 4 different nodes. on a 5th node, 16 client processes are launched. These clients obtain server address through an out-of-band mechanism (PMIx), do some business, then exit. The clients go through this (launch, do something, exit) loop for 5 or 6 cycles fine, then the server side starts to print out those messages. So the clients disconnect by simply exiting.

**Comment by shefty** [comment]
Does the test use RDM EPs?

**Comment by yulujia** [comment]
I believe so. We use Mercury, it passes  FI_EP_RDM as a hint to fi_getinro():
 https://github.com/mercury-hpc/mercury/blob/f0b9f992793be46f1c6ae47b30d1c3ccb525cfbf/src/na/na_ofi.c#L1395

**Comment by shefty** [comment]
Sounds like either an issue in the app or provider not updating the AV correctly to remove old addresses.  @a-ilango - Does rxm detect when the underlying connection to a specific peer address changes?  @yulujia - Do you know if the clients request the same local address, or are happy getting a system assigned one?

**Comment by a-ilango** [comment]
RxM can detect connection changes (assuming the underlying provider throws FI_SHUTDOWN event). 

The error code: 24 (EMFILE: too many open files) suggest the server program is hitting a limit in # of open file descriptors. @yulujia can you check the "ulimit -n" on the system and try increasing it?

**Comment by shefty** [comment]
I'm guessing that the server is building up a large number of disconnected sockets inside the rxm av.  Unless something tries to use those sockets (e.g. send a message on them), I don't think anything will detect that they are no longer usable.  Increasing ulimit may just move the problem out X more connections.

**Comment by a-ilango** [comment]
If the sockets are disconnected they shouldn't count towards the ulimit, right? I think just having those "stale addresses" in AV shouldn't cause an issue.

**Comment by shefty** [comment]
The app still has a valid fd for the socket.

**Comment by a-ilango** [comment]
Sorry, I didn't realize this issue is observed in the specific commit that postpones the closing of fds. That can result in hitting the fd limit.

**Comment by yulujia** [comment]
@shefty 
> Do you know if the clients request the same local address, or are happy getting a system assigned one?

the clients are happy with a system assigned address. Each client process uses a different URI in each client run.

@a-ilango 
> can you check the "ulimit -n" on the system and try increasing it?
ulimit -n shows me 1024. I set it to 4096 by ulimit -n 4096 and re-run the test, this time the server side doesn't print out the warning message, but on the 26-th run the client got stuck, the cient log shows this message repeatedly:

na_ofi_msg_send_unexpected(): fi_tsend(unexpected) failed, rc: -113(No route to host)

> Sorry, I didn't realize this issue is observed in the specific commit that postpones the closing of fds. That can result in hitting the fd limit.

do you mean there's a commit that doesn't have this issue?

**Comment by a-ilango** [comment]
> na_ofi_msg_send_unexpected(): fi_tsend(unexpected) failed, rc: -113(No route to host)

That's weird. You could turn on logging (FI_LOG_LEVEL=warn) to see if that shows any issue.

> do you mean there's a commit that doesn't have this issue?

Yes, I believe if you tried one commit before 59beba9419adf2ae2dfd7f91598fe7efe78519da you may not hit the issue.

**Comment by yulujia** [comment]
@a-ilango using commit ca7f08c03 and ulimit -n 4096, I still get a similar message on the 28-th or 29-th client run:

na_ofi_get(): fi_readmsg() failed, rc: -113(No route to host)

**Comment by a-ilango** [comment]
But you don't see the -24 error code anymore, right?

**Comment by yulujia** [comment]
right, I didn't see the  -24 error code.

**Comment by a-ilango** [comment]
> na_ofi_get(): fi_readmsg() failed, rc: -113(No route to host)

Can you share the logs for this test? If FI_LOG_LEVEL=warn doesn't show any issue, bump it up to FI_LOG_LEVEL=debug (libfabric needs to be configured with --enable-debug for this).

I'll work on a fix to address the -24 error.

**Comment by yulujia** [comment]
@a-ilango @shefty have you got a fix for the -24 error?

for the -133 error, I enabled FI_LOG_LEVEL=debug and ran the test again, the ofi log is here: https://app.box.com/s/l7xsfrqxwj90dgayuoro7srcfpbp34ax

the corresponding error in the application debug log:
```
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] vos  DBUG src/vos/vos_io.c:130 vos_ioc_reserve_init() alloc(calloc) 'ioc->ic_umoffs': 8 at 0x7f63534d10c0.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] vos  DBUG src/vos/vos_io.c:137 vos_ioc_reserve_init() alloc(calloc) 'ioc->ic_actv': 128 at 0x7f63534d10e0.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] bio  DBUG src/bio/bio_buffer.c:183 bio_iod_alloc() alloc(calloc) 'biod': 88 at 0x7f63534d1170.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] bio  DBUG src/bio/bio_buffer.c:191 bio_iod_alloc() alloc(calloc) 'biod->bd_sgls': 16 at 0x7f63534d11d0.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] vos  DBUG src/include/daos_srv/bio.h:141 bio_sgl_init() alloc(calloc) 'sgl->bs_iovs': 32 at 0x7f63534d11f0.
10/07-16:36:26.45 wolf-24 DAOS[8122/8127] common DBUG src/common/misc.c:67 daos_sgl_fini() free 'sgl->sg_iovs' at 0x7f6375cf7e30.
10/07-16:36:26.45 wolf-24 DAOS[8122/8138] rpc  DBUG src/cart/crt_rpc.c:247 crt_rpc_priv_alloc() alloc(calloc) 'rpc_priv': 1104 at 0x7f63574ee390.
10/07-16:36:26.45 wolf-24 DAOS[8122/8138] rpc  DBUG src/cart/crt_rpc.c:258 crt_rpc_priv_alloc(0x7f63574ee390)  [opc=0x401000b rank:xid=0:0x0 tag=0] (opc: 0x401000b rpc_pub: 0x7f63574ee390) allocated.
10/07-16:36:26.45 wolf-24 DAOS[8122/8138] object DBUG src/object/srv_obj_remote.c:151 ds_obj_remote_update() 1153784526745370624.15455983676972308673.11 forwarding to rank:2 tag:7.
10/07-16:36:26.45 wolf-24 DAOS[8122/8138] rpc  DBUG src/cart/crt_rpc.c:1183 crt_req_send(0x7f63574ee390)  [opc=0x401000b rank:xid=2:0x7fc tag=7] addref to 2.
10/07-16:36:26.45 wolf-24 DAOS[8122/8138] rpc  DBUG src/cart/crt_rpc.c:1207 crt_req_send(0x7f63574ee390)  [opc=0x401000b rank:xid=2:0x7fc tag=7] submitted.
10/07-16:36:26.45 wolf-24 DAOS[8122/8138] rpc  DBUG src/cart/crt_context.c:887 crt_context_req_track(0x7f63574ee390)  [opc=0x401000b rank:xid=2:0x7fc tag=7] addref to 3.
10/07-16:36:26.45 wolf-24 DAOS[8122/8138] rpc  DBUG src/cart/crt_context.c:589 crt_req_timeout_track(0x7f63574ee390)  [opc=0x401000b rank:xid=2:0x7fc tag=7] addref to 4.
10/07-16:36:26.45 wolf-24 DAOS[8122/8138] rpc  DBUG src/cart/crt_rpc.c:1504 timeout_bp_node_enter(0x7f63574ee390)  [opc=0x401000b rank:xid=2:0x7fc tag=7] entering the timeout binheap.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] vos  DBUG src/vos/vos_io.c:1031 iod_reserve() media 0 offset 4203600 size 1048576
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] object DBUG src/object/srv_obj.c:216 ds_bulk_transfer() bulk_op:105 sgl_nr1
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] common DBUG src/common/misc.c:44 daos_sgl_init() alloc(calloc) 'sgl->sg_iovs': 24 at 0x7f63534d1490.
10/07-16:36:26.45 wolf-24 DAOS[8122/8137] rpc  DBUG src/cart/crt_rpc.c:473 crt_req_addref(0x7f635e1bff10)  [opc=0x4010000 rank:xid=0:0x0 tag=5] addref to 3.
10/07-16:36:26.45 wolf-24 DAOS[8122/8137] hg   DBUG src/cart/crt_hg.c:1614 crt_hg_bulk_transfer() alloc(calloc) 'bulk_cbinfo': 24 at 0x7f635f06b950.
10/07-16:36:26.45 wolf-24 DAOS[8122/8137] hg   DBUG src/cart/crt_hg.c:1617 crt_hg_bulk_transfer() alloc(calloc) 'bulk_desc_dup': 56 at 0x7f635e1c6470.
10/07-16:36:26.45 wolf-24 DAOS[8122/8138] rpc  DBUG src/cart/crt_rpc.c:891 crt_req_ep_lc_lookup() free 'uri' at (nil).
10/07-16:36:26.45 wolf-24 DAOS[8122/8138] hg   DBUG src/cart/crt_hg.c:235 crt_hg_pool_get() hg_pool 0x7f63540268e8, remove, chp_num 15.
10/07-16:36:26.45 wolf-24 DAOS[8122/8138] hg   DBUG src/cart/crt_hg.c:1188 crt_hg_req_send(0x7f63574ee390)  [opc=0x401000b rank:xid=2:0x7fc tag=7] addref to 5.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] rpc  DBUG src/cart/crt_rpc.c:473 crt_req_addref(0x7f63534d09b0)  [opc=0x401000b rank:xid=1:0x7f8 tag=7] addref to 2.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] hg   DBUG src/cart/crt_hg.c:1614 crt_hg_bulk_transfer() alloc(calloc) 'bulk_cbinfo': 24 at 0x7f63534d1520.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] hg   DBUG src/cart/crt_hg.c:1617 crt_hg_bulk_transfer() alloc(calloc) 'bulk_desc_dup': 56 at 0x7f63534d1540.
10/07-16:36:26.45 wolf-24 DAOS[8122/8137] common DBUG src/common/misc.c:67 daos_sgl_fini() free 'sgl->sg_iovs' at 0x7f635f069020.
10/07-16:36:26.45 wolf-24 DAOS[8122/8138] hg   DBUG src/cart/crt_hg.c:1200 crt_hg_req_send(0x7f63574ee390)  [opc=0x401000b rank:xid=2:0x7fc tag=7] sent to rank 2 uri: (null)
10/07-16:36:26.45 wolf-24 DAOS[8122/8138] hg   DBUG src/cart/crt_hg.c:1217 crt_hg_req_send(0x7f63574ee390)  [opc=0x401000b rank:xid=2:0x7fc tag=7] decref to 4.
10/07-16:36:26.45 wolf-24 DAOS[8122/8138] rpc  DBUG src/cart/crt_rpc.c:1239 crt_req_send(0x7f63574ee390)  [opc=0x401000b rank:xid=2:0x7fc tag=7] decref to 3.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] hg   ERR  # NA -- Error -- /home/yulujia/codes/daos-fresh-cart-764-tcp/_build.external/mercury/src/na/na_ofi.c:4617
 # na_ofi_get(): fi_readmsg() failed, rc: -113(No route to host)
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] hg   ERR  # HG -- Error -- /home/yulujia/codes/daos-fresh-cart-764-tcp/_build.external/mercury/src/mercury_bulk.c:804
 # hg_bulk_transfer_pieces(): Could not transfer data
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] hg   ERR  # HG -- Error -- /home/yulujia/codes/daos-fresh-cart-764-tcp/_build.external/mercury/src/mercury_bulk.c:971
 # hg_bulk_transfer(): Could not transfer data pieces
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] hg   ERR  # HG -- Error -- /home/yulujia/codes/daos-fresh-cart-764-tcp/_build.external/mercury/src/mercury_bulk.c:2013
 # HG_Bulk_transfer_id(): Could not transfer data
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] hg   ERR  src/cart/crt_hg.c:1655 crt_hg_bulk_transfer() HG_Bulk_(bind)transfer failed, hg_ret: 1.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] hg   DBUG src/cart/crt_hg.c:1656 crt_hg_bulk_transfer() free 'bulk_cbinfo' at 0x7f63534d1520.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] hg   DBUG src/cart/crt_hg.c:1657 crt_hg_bulk_transfer() free 'bulk_desc_dup' at 0x7f63534d1540.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] bulk ERR  src/cart/crt_bulk.c:231 crt_bulk_bind_transfer() crt_hg_bulk_transfer failed, rc: -1020.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] object ERR  src/object/srv_obj.c:315 ds_bulk_transfer() crt_bulk_transfer 0 error (-1020).
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] rpc  DBUG src/cart/crt_rpc.c:491 crt_req_decref(0x7f63534d09b0)  [opc=0x401000b rank:xid=1:0x7f8 tag=7] decref to 1.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] common DBUG src/common/misc.c:67 daos_sgl_fini() free 'sgl->sg_iovs' at 0x7f63534d1490.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] bio  DBUG src/include/daos_srv/bio.h:151 bio_sgl_fini() free 'sgl->bs_iovs' at 0x7f63534d11f0.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] bio  DBUG src/bio/bio_buffer.c:216 bio_iod_free() free 'biod->bd_sgls' at 0x7f63534d11d0.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] bio  DBUG src/bio/bio_buffer.c:217 bio_iod_free() free 'biod' at 0x7f63534d1170.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] vos  DBUG src/vos/vos_io.c:106 vos_ioc_reserve_fini() free 'ioc->ic_actv' at 0x7f63534d10e0.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] vos  DBUG src/vos/vos_io.c:111 vos_ioc_reserve_fini() free 'ioc->ic_umoffs' at 0x7f63534d10c0.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] vos  DBUG src/vos/vos_io.c:156 vos_ioc_destroy() free 'ioc' at 0x7f63534d1030.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] object ERR  src/object/srv_obj.c:67 ds_obj_rw_complete() 1153784526745370624.15455983676972308673.28Update end failed: -1020
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] vos  DBUG src/vos/vos_obj.c:1497 vos_oi_get_attr() Get attributes 1153784526745370624.15455983676972308673.28, epoch 1570491386449428481
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] vos  DBUG src/vos/vos_obj_cache.c:210 vos_obj_hold() Try to hold cont=e0752242, obj=1153784526745370624.15455983676972308673.28
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] vos  DBUG src/vos/vos_obj_cache.c:129 obj_lop_print_key() pool=7db426a1 cont=e0752242, obj=1153784526745370624.15455983676972308673.28
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] common DBUG src/common/lru.c:269 daos_lru_ref_hold() Entry not found adding it to LRU
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] vos  DBUG src/vos/vos_obj_cache.c:74 obj_lop_alloc() cont=e0752242, obj=1153784526745370624.15455983676972308673.28
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] vos  DBUG src/vos/vos_obj_cache.c:76 obj_lop_alloc() alloc(calloc) 'obj': 128 at 0x7f63534d10e0.
10/07-16:36:26.45 wolf-24 DAOS[8122/8139] common DBUG src/common/lru.c:275 daos_lru_ref_hold() Inserting into LRU Hash table
```

**Comment by a-ilango** [comment]
@yulujia can you try your test on #5348 ? That should fix the -24 error. The libfabric debug logs for the -113 error doesn't show anything problematic.

**Comment by yulujia** [comment]
@a-ilango with  #5348 I still see the -24 error:

```
fi_readmsg() failed, rc: -24(Too many open files)
```

Any suggestions on dealing with the -113 error?

**Comment by a-ilango** [comment]
I'm not sure about -113 error as libfabric logs doesn't show any issue. Can you trace where the error is coming from?

**Comment by yulujia** [comment]
@shefty is there any progress on this patch?

**Comment by shefty** [comment]
no update
