### ISSUE TITLE
prov/psm2 memory leaks with 1.9.0rc1

### ISSUE THREAD

**Issue by soumagne** [ofiwg/libfabric#5405]
Looks like that was a provider I had not gone through yet :) I'm getting several memory leaks from the psm2 provider with latest 1.9.0rc1, I assume it's the same with previous tags and master seems to be the same as of now. A few come from opa-psm2 but most of them are from the provider itself. Note that the same test is fine with rxm/tcp and sockets (no leaks in those cases).

On client I'm getting:
```bash
[soumagne@beboplogin2 build_new_gcc]$ mpirun -np 1 ./bin/hg_test_rpc -c ofi -p psm2 
# Using info string: ofi+psm2
# Target name read: ofi+psm2://1290d02:0
...
Direct leak of 890941 byte(s) in 9 object(s) allocated from:
    #0 0x2b600389e5d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2b60067c3040 in psmi_malloc_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1406

Direct leak of 655552 byte(s) in 3 object(s) allocated from:
    #0 0x2b600389f2b8 in __interceptor_posix_memalign /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:155
    #1 0x2b60067c309d in psmi_memalign_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1474
    #2 0x2b60067d143f in ips_scbctrl_init /blues/gpfs/home/soumagne/workspace/opa-psm2/ptl_ips/ips_scb.c:121

Direct leak of 16384 byte(s) in 1 object(s) allocated from:
    #0 0x2b600389f2b8 in __interceptor_posix_memalign /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:155
    #1 0x2b60067c309d in psmi_memalign_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1474
    #2 0x2b60067b6a21 in amsh_init /blues/gpfs/home/soumagne/workspace/opa-psm2/ptl_am/am_reqrep_shmem.c:2471

Direct leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x2b600389e7b8 in __interceptor_calloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:95
    #1 0x2b60056ee6d3 in psmx2_av_open prov/psm2/src/psmx2_av.c:1048

Direct leak of 48 byte(s) in 3 object(s) allocated from:
    #0 0x2b600389e7b8 in __interceptor_calloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:95
    #1 0x2b60056e434e in psmx2_getinfo prov/psm2/src/psmx2_init.c:536

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x2b600389e5d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2b60056ed63b in psmx2_set_epaddr_context prov/psm2/src/psmx2_av.c:185

Direct leak of 30 byte(s) in 1 object(s) allocated from:
    #0 0x2b600389e5d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2b60067ece66 in sysfs_init /blues/gpfs/home/soumagne/workspace/opa-psm2/opa/opa_sysfs.c:89
    #2 0x2b60035a18f2 in _dl_init_internal (/lib64/ld-linux-x86-64.so.2+0xf8f2)
    #3 0x7ffd5731b208  ([stack]+0x20208)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x2b600389e5d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2b60067c3040 in psmi_malloc_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1406

SUMMARY: AddressSanitizer: 1564051 byte(s) leaked in 20 allocation(s).
```
On server, I'm getting:
```bash
[soumagne@beboplogin3 build_new_gcc]$ mpirun -np 1 ./bin/hg_test_server -c ofi -p psm2 
# Using info string: ofi+psm2
# Waiting for client...

=================================================================
==80921==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 890941 byte(s) in 9 object(s) allocated from:
    #0 0x2b8c91a925d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2b8c949b7040 in psmi_malloc_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1406

Direct leak of 655552 byte(s) in 3 object(s) allocated from:
    #0 0x2b8c91a932b8 in __interceptor_posix_memalign /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:155
    #1 0x2b8c949b709d in psmi_memalign_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1474
    #2 0x2b8c949c543f in ips_scbctrl_init /blues/gpfs/home/soumagne/workspace/opa-psm2/ptl_ips/ips_scb.c:121

Direct leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x2b8c91a927b8 in __interceptor_calloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:95
    #1 0x2b8c938e26d3 in psmx2_av_open prov/psm2/src/psmx2_av.c:1048

Direct leak of 112 byte(s) in 1 object(s) allocated from:
    #0 0x2b8c91a927b8 in __interceptor_calloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:95
    #1 0x2b8c938df81a in psmx2_cq_open prov/psm2/src/psmx2_cq.c:2000

Direct leak of 48 byte(s) in 3 object(s) allocated from:
    #0 0x2b8c91a927b8 in __interceptor_calloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:95
    #1 0x2b8c938d834e in psmx2_getinfo prov/psm2/src/psmx2_init.c:536

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x2b8c91a925d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2b8c938e163b in psmx2_set_epaddr_context prov/psm2/src/psmx2_av.c:185

Direct leak of 30 byte(s) in 1 object(s) allocated from:
    #0 0x2b8c91a925d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2b8c949e0e66 in sysfs_init /blues/gpfs/home/soumagne/workspace/opa-psm2/opa/opa_sysfs.c:89
    #2 0x2b8c917958f2 in _dl_init_internal (/lib64/ld-linux-x86-64.so.2+0xf8f2)
    #3 0x7ffc621381ea  ([stack]+0x201ea)

Indirect leak of 21616 byte(s) in 193 object(s) allocated from:
    #0 0x2b8c91a927b8 in __interceptor_calloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:95
    #1 0x2b8c938dbb90 in psmx2_cq_alloc_event prov/psm2/src/psmx2_cq.c:76

Indirect leak of 6832 byte(s) in 61 object(s) allocated from:
    #0 0x2b8c91a927b8 in __interceptor_calloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:95
    #1 0x2b8c938df81a in psmx2_cq_open prov/psm2/src/psmx2_cq.c:2000

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x2b8c91a925d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2b8c949b7040 in psmi_malloc_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1406

SUMMARY: AddressSanitizer: 1576227 byte(s) leaked in 274 allocation(s).
```

**Comment by j-xiong** [comment]
@soumagne Could you test agianst PR #5411? The leaks from the provider have been addressed.

**Comment by soumagne** [comment]
@j-xiong sorry the delay in getting back to this. I'm testing it now.

**Comment by soumagne** [comment]
Thanks! It definitely is better but still some leaks it looks like. This is with PR #5411 on client:
```bash
[soumagne@beboplogin3 build_new_gcc]$ mpirun -np 1 ./bin/hg_test_rpc -c ofi -p psm2
# Using info string: ofi+psm2
# Target name read: ofi+psm2://1390d02:0
[...]
=================================================================
==89344==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 890941 byte(s) in 9 object(s) allocated from:
    #0 0x2ae74dd585d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2ae750c7d040 in psmi_malloc_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1406

Direct leak of 655552 byte(s) in 3 object(s) allocated from:
    #0 0x2ae74dd592b8 in __interceptor_posix_memalign /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:155
    #1 0x2ae750c7d09d in psmi_memalign_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1474
    #2 0x2ae750c8b43f in ips_scbctrl_init /blues/gpfs/home/soumagne/workspace/opa-psm2/ptl_ips/ips_scb.c:121

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x2ae74dd585d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2ae74fba6bf0 in psmx2_set_epaddr_context prov/psm2/src/psmx2_av.c:187

Direct leak of 30 byte(s) in 1 object(s) allocated from:
    #0 0x2ae74dd585d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2ae750ca6e66 in sysfs_init /blues/gpfs/home/soumagne/workspace/opa-psm2/opa/opa_sysfs.c:89
    #2 0x2ae74da5b8f2 in _dl_init_internal (/lib64/ld-linux-x86-64.so.2+0xf8f2)
    #3 0x7fff8f67920d  ([stack]+0x2020d)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x2ae74dd585d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2ae750c7d040 in psmi_malloc_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1406

SUMMARY: AddressSanitizer: 1546595 byte(s) leaked in 15 allocation(s).
```
On server:
```bash
[soumagne@beboplogin4 build_new_gcc]$ mpirun -np 1 ./bin/hg_test_server -c ofi -p psm2
# Using info string: ofi+psm2
# Waiting for client...

=================================================================
==30461==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 890941 byte(s) in 9 object(s) allocated from:
    #0 0x2abc41d295d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2abc44c4e040 in psmi_malloc_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1406

Direct leak of 655552 byte(s) in 3 object(s) allocated from:
    #0 0x2abc41d2a2b8 in __interceptor_posix_memalign /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:155
    #1 0x2abc44c4e09d in psmi_memalign_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1474
    #2 0x2abc44c5c43f in ips_scbctrl_init /blues/gpfs/home/soumagne/workspace/opa-psm2/ptl_ips/ips_scb.c:121

Direct leak of 16384 byte(s) in 1 object(s) allocated from:
    #0 0x2abc41d2a2b8 in __interceptor_posix_memalign /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:155
    #1 0x2abc44c4e09d in psmi_memalign_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1474
    #2 0x2abc44c41a21 in amsh_init /blues/gpfs/home/soumagne/workspace/opa-psm2/ptl_am/am_reqrep_shmem.c:2471

Direct leak of 112 byte(s) in 1 object(s) allocated from:
    #0 0x2abc41d297b8 in __interceptor_calloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:95
    #1 0x2abc43b7698a in psmx2_cq_open prov/psm2/src/psmx2_cq.c:2006

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x2abc41d295d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2abc43b77bf0 in psmx2_set_epaddr_context prov/psm2/src/psmx2_av.c:187

Direct leak of 30 byte(s) in 1 object(s) allocated from:
    #0 0x2abc41d295d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2abc44c77e66 in sysfs_init /blues/gpfs/home/soumagne/workspace/opa-psm2/opa/opa_sysfs.c:89
    #2 0x2abc41a2c8f2 in _dl_init_internal (/lib64/ld-linux-x86-64.so.2+0xf8f2)
    #3 0x7ffcc482d1f8  ([stack]+0x201f8)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x2abc41d295d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2abc44c4e040 in psmi_malloc_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1406

SUMMARY: AddressSanitizer: 1563091 byte(s) leaked in 17 allocation(s).
```

**Comment by j-xiong** [comment]
Thanks for the result! I have updated PR #5411 which I believe should eliminate the remaining leaks related to "psmx2_av.c:187". The single object leak for "psmx2_cq.c:2006" is more difficult to iron out. I will leave that alone for now, together with those leaks related to the PSM2 library.

**Comment by soumagne** [comment]
thanks! yes it did eliminate one but still have the one from the CQ though it looks like. Here is the result now on client:
```bash
[soumagne@beboplogin2 build_new_gcc]$ mpirun -np 1 ./bin/hg_test_rpc -c ofi -p psm2
# Using info string: ofi+psm2
# Target name read: ofi+psm2://4660d02:0
[...]
=================================================================
==194592==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 890941 byte(s) in 9 object(s) allocated from:
    #0 0x2b6ae4b935d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2b6ae7ab8040 in psmi_malloc_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1406

Direct leak of 655552 byte(s) in 3 object(s) allocated from:
    #0 0x2b6ae4b942b8 in __interceptor_posix_memalign /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:155
    #1 0x2b6ae7ab809d in psmi_memalign_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1474
    #2 0x2b6ae7ac643f in ips_scbctrl_init /blues/gpfs/home/soumagne/workspace/opa-psm2/ptl_ips/ips_scb.c:121

Direct leak of 16384 byte(s) in 1 object(s) allocated from:
    #0 0x2b6ae4b942b8 in __interceptor_posix_memalign /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:155
    #1 0x2b6ae7ab809d in psmi_memalign_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1474
    #2 0x2b6ae7aaba21 in amsh_init /blues/gpfs/home/soumagne/workspace/opa-psm2/ptl_am/am_reqrep_shmem.c:2471

Direct leak of 30 byte(s) in 1 object(s) allocated from:
    #0 0x2b6ae4b935d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2b6ae7ae1e66 in sysfs_init /blues/gpfs/home/soumagne/workspace/opa-psm2/opa/opa_sysfs.c:89
    #2 0x2b6ae48968f2 in _dl_init_internal (/lib64/ld-linux-x86-64.so.2+0xf8f2)
    #3 0x7fffc5a5b200  ([stack]+0x20200)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x2b6ae4b935d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2b6ae7ab8040 in psmi_malloc_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1406

SUMMARY: AddressSanitizer: 1562939 byte(s) leaked in 15 allocation(s).
```
and on server:
```bash
[soumagne@beboplogin2 build_new_gcc]$ mpirun -np 1 ./bin/hg_test_server -c ofi -p psm2
# Using info string: ofi+psm2
# Waiting for client...

=================================================================
==192304==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 890941 byte(s) in 9 object(s) allocated from:
    #0 0x2b5de17d45d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2b5de46f9040 in psmi_malloc_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1406

Direct leak of 655552 byte(s) in 3 object(s) allocated from:
    #0 0x2b5de17d52b8 in __interceptor_posix_memalign /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:155
    #1 0x2b5de46f909d in psmi_memalign_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1474
    #2 0x2b5de470743f in ips_scbctrl_init /blues/gpfs/home/soumagne/workspace/opa-psm2/ptl_ips/ips_scb.c:121

Direct leak of 112 byte(s) in 1 object(s) allocated from:
    #0 0x2b5de17d47b8 in __interceptor_calloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:95
    #1 0x2b5de362199a in psmx2_cq_open prov/psm2/src/psmx2_cq.c:2006

Direct leak of 30 byte(s) in 1 object(s) allocated from:
    #0 0x2b5de17d45d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2b5de4722e66 in sysfs_init /blues/gpfs/home/soumagne/workspace/opa-psm2/opa/opa_sysfs.c:89
    #2 0x2b5de14d78f2 in _dl_init_internal (/lib64/ld-linux-x86-64.so.2+0xf8f2)
    #3 0x7ffcdd9ee1f7  ([stack]+0x201f7)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x2b5de17d45d0 in __interceptor_malloc /blues/gpfs/software/centos7/spack/var/spack/stage/gcc-8.2.0-g7hppkzhsqueybppw7afv4pnvh4dgrna/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x2b5de46f9040 in psmi_malloc_internal /blues/gpfs/home/soumagne/workspace/opa-psm2/psm_utils.c:1406

SUMMARY: AddressSanitizer: 1546667 byte(s) leaked in 15 allocation(s).
```

**Comment by j-xiong** [comment]
Thanks for the verification!
