### ISSUE TITLE
Lack of libibverbs driver causes failure for usnic devices

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#975]
Here's a new failure mode:

```
$ ./simple/fi_info
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs2
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs1
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs0
librdmacm: Fatal: no RDMA devices found
fi_getinfo(): 173, -19 (No such device)
```

This is happening because Cisco is no longer shipping the usnic provider for libibverbs.  Specifically, libibverbs will see usnic devices in /sys/class/infiniband, but it won't be able to find a userspace plugin that wants to claim them.

This causes both warnings to stderr (which is crummy in itself, but not libfabric's problem, strictly speaking) and causes `fi_getinfo()`'s use of the verbs provider to fail with -ENODEV (because `rdma_get_devices()` returns -ENODEV), thereby causing fi_getinfo() to fail altogether.

This happens even though the usnic libfabric provider had previously returned valid output (i.e., multiple `fi_info` instances full of yummy usNIC info).

If you force just the usnic provider, everything works fine (e.g., `./simple_fi_info -f usnic`), but that isn't the point: the default settings of the verbs provider cause false failures.

Can this be fixed, especially before 1.0 is released?

**Comment by shefty** [comment]
The verbs provider can be updated to return ENODATA in order to avoid this problem.  I'm not sure what to do about the stderr output.

**Comment by jsquyres** [comment]
I just filed PR #978 to fix the verbs provider and libibverbs stderr warnings.  However, I'm now left with a librdmacm warning:

```
$ ./simple/fi_info
librdmacm: Fatal: unable to open RDMA device
---
fi_info:
    caps: [ FI_SOURCE, FI_MSG, FI_RECV, FI_SEND ]
    mode: [ FI_LOCAL_MR, FI_MSG_PREFIX ]
    fi_addr_format: FI_SOCKADDR_IN
...etc.
```

@shefty Is there a way to squelch that librdmacm stderr message?

**Comment by shefty** [comment]
PR #984 should fix the librdmacm messages

**Comment by jsquyres** [comment]
#984 didn't fix it, unfortunately -- see https://github.com/ofiwg/libfabric/pull/978#issuecomment-97209325

**Comment by jsquyres** [comment]
Yay!

```
$ ./simple/fi_info
---
fi_info:
    caps: [ FI_SOURCE, FI_MSG, FI_RECV, FI_SEND ]
    mode: [ FI_LOCAL_MR, FI_MSG_PREFIX ]
    fi_addr_format: FI_SOCKADDR_IN
    src_addrlen: 16
    dest_addrlen: 0
...etc.
```
